after_success: 
  - "npm run coveralls"
before_script: 
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - "npm run migrate"
  - "npm run seed:all"
branches: 
  only: 
    - develop
cache: 
  directories: 
    - node_modules
env: 
  global: 
    - "export NODE_ENV=test"
language: node_js
node_js: 
  - stable
services: 
  - postgresql