language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
branches:
  only:
  - develop
before_script:
  - npm run migrate
  - npm run seed:all
after_success:
  - npm run coveralls