after_success: 
  - "npm run coveralls"
before_script: 
  - "npm run migrate"
  - "npm run seed:all"
branches: 
  only: 
    - develop
cache: 
  directories: 
    - node_modules
language: node_js
node_js: 
  - stable
services: 
  - postgresql

