export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_SINGLE_ARTICLE = 'GETTING SINGLE ARTICLE';
export const ARTICLE_LOADING = 'ARTICLE(S) LOADING';
export const GET_ARTICLE_ERROR = 'ERROR GETTING ARTICLE';
