export const PASSWORD_REQUEST_LOADING = 'PASSWORD_REQUEST_LOADING';
export const PASSWORD_REQUEST_SUCCESS = 'PASSWORD_REQUEST_SUCCESS';
export const PASSWORD_REQUEST_FAILED = 'PASSWORD_REQUEST_FAILED';
